defaults:
  - vehicle: default
  - envs: default 
  - reward: ???
  - agent: sac
  - buffer: off_policy

num_episodes: 1000
num_steps: 10000
batch_size: 128
save_ckpt_dir: ./ckpts/

eval_interval: 10
num_eval_episodes: 1

use_wandb: False
wandb_project: f1tenth
wandb_run_name: ???
wandb_mode: online


